export const USER_SIGNUP_PROCESSING = "USER_SIGNUP_PROCESSING"
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"

export const USER_LOGIN_PROCESSING = "USER_LOGIN_PROCESSING"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"

